/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lilbank

import java.lang.NumberFormatException
import java.math.BigDecimal

import Account
import Bank
import lilbank.adapters.AccountRepository

fun getBank() : Bank {
    return Bank("Bank of the Universe")
}

fun createAccount(bank: Bank, repository: AccountRepository) {
    println("Create new account for ${bank.name}")

    print("Name: ")
    val name = readLine()!!
    val account = Account(name=name)
    bank.addAccount(account)
    repository.save(account)

    println("Account ${account.name} with id ${account.id} created")
}

fun deposit(bank: Bank, repository: AccountRepository) {
    print("Account id: ")
    val accountId = try { readLine()!!.toInt() } catch (e: NumberFormatException) { println("Invalid int") }
    print("Amount: ")
    val amount = try { readLine()!!.toBigDecimal() } catch (e: NumberFormatException) { println("Invalid currency") }

    if (accountId is Int && amount is BigDecimal) {
        val account = bank.accounts[accountId]

        if (account != null) {
            account.deposit(amount)
            repository.save(account)
            println("Deposited $amount! Balance is now ${account.balance}")
        }
    }
}

fun listAccounts(repository: AccountRepository) {
    repository.list().forEach {
        it.printInfo()
    }
}

fun main() {
    val bank = getBank()
    println("Welcome to da '${bank.name}'!")

    // Load accounts
    val accountRepo = AccountRepository()
    accountRepo.list().forEach {
        bank.addAccount(it)
    }

    while (true) {
        println("----")
        print("Options:\n1) Create new account\n2) List accounts\n3) Deposit\n4) Withdraw\n> ")

        when (try { readLine()!!.toInt() } catch (e: NumberFormatException) { println("Invalid int") }) {
            1 -> createAccount(bank, accountRepo)
            2 -> listAccounts(accountRepo)
            3 -> deposit(bank, accountRepo)
        }
    }
}
